"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import json
import logging
import os
import ssl as _ssl
from celery.schedules import crontab
from decimal import Decimal as _Decimal
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', '0').lower() in ('1', 'true')
TEST = os.environ.get('TEST', '0').lower() in ('1', 'true')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Publicly accessible base URL for this application (used for provider callbacks, etc.)
BASE_URL = os.environ.get('BASE_URL', '')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'django_celery_beat',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'app.middleware.RequestLoggingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app.middleware.ClerkTenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'app.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Connection pool (psycopg3 native) — bounded per-process pool for ASGI safety.
# Disable with DB_POOL=false for local dev where pooling is unnecessary.
_DB_POOL_ENABLED = os.environ.get('DB_POOL', 'true').lower() in ('1', 'true')
_DB_POOL_MIN = int(os.environ.get('DB_POOL_MIN_SIZE', '2'))
_DB_POOL_MAX = int(os.environ.get('DB_POOL_MAX_SIZE', '8'))
_DB_POOL_TIMEOUT = int(os.environ.get('DB_POOL_TIMEOUT', '10'))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': os.environ.get('POSTGRES_PORT'),
        'CONN_MAX_AGE': None if _DB_POOL_ENABLED else int(os.environ.get('DB_CONN_MAX_AGE', '0')),
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            **({'sslmode': 'require'} if not DEBUG else {}),
        },
        **({'POOL': {
            'min_size': _DB_POOL_MIN,
            'max_size': _DB_POOL_MAX,
            'timeout': _DB_POOL_TIMEOUT,
        }} if _DB_POOL_ENABLED else {}),
    }
}


# Custom user model
AUTH_USER_MODEL = 'app.User'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Security headers (env-driven so local dev is unaffected — defaults are safe for dev)
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
# NOTE: SECURE_SSL_REDIRECT intentionally omitted — must stay False on Azure App Service
# (Azure terminates TLS at the load balancer; setting True causes infinite redirect loops)


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'app.authentication.ClerkJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'app.exception_handler.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'app.pagination.StandardPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('THROTTLE_RATE_ANON', '1000/min'),
        'user': os.environ.get('THROTTLE_RATE_USER', '1000/min'),
        'sms': os.environ.get('THROTTLE_RATE_SMS', '100/min'),
        'import': os.environ.get('THROTTLE_RATE_IMPORT', '10/min'),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Reach API',
    'VERSION': '2.0.0',
    'DESCRIPTION': 'SMS/MMS scheduling and contact management API.',
}


# CORS
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')
CORS_EXPOSE_HEADERS = ['Content-Disposition']


# Clerk
CLERK_FRONTEND_API = os.environ.get('CLERK_FRONTEND_API', '')
CLERK_SECRET_KEY = os.environ.get('CLERK_SECRET_KEY', '')
CLERK_WEBHOOK_SIGNING_SECRET = os.environ.get('CLERK_WEBHOOK_SIGNING_SECRET', '')
CLERK_AUTHORIZED_PARTIES = os.environ.get('CLERK_AUTHORIZED_PARTIES', 'http://localhost:5173').split(',')


# Billing
FREE_CREDIT_AMOUNT = _Decimal(os.environ.get('FREE_CREDIT_AMOUNT', '5.00'))
SMS_RATE = _Decimal(os.environ.get('SMS_RATE', '0.10'))
MMS_RATE = _Decimal(os.environ.get('MMS_RATE', '0.50'))

# Metered billing provider (auto-selects Stripe when STRIPE_SECRET_KEY is set)
METERED_BILLING_PROVIDER_CLASS = (
    'app.utils.stripe.StripeMeteredBillingProvider'
    if os.environ.get('STRIPE_SECRET_KEY')
    else 'app.utils.metered_billing.MockMeteredBillingProvider'
)
METERED_BILLING_PROVIDER_CONFIG = {
    'secret_key': os.environ.get('STRIPE_SECRET_KEY', ''),
    'webhook_secret': os.environ.get('STRIPE_WEBHOOK_SECRET', ''),
}


# Celery (local dev: redis in docker-compose; production: Azure Cache for Redis)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True          # Never lose tasks on worker crash
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Fair dispatch
CELERY_TASK_DEFAULT_QUEUE = 'default'  # Match worker's -Q default,messages
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_connect_timeout': 30,
    'socket_timeout': 30,
    'socket_keepalive': True,
}
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    'socket_connect_timeout': 30,
    'socket_timeout': 30,
    'socket_keepalive': True,
}
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Message retry policy
MESSAGE_MAX_RETRIES = int(os.environ.get('MESSAGE_MAX_RETRIES', '3'))
MESSAGE_RETRY_BASE_DELAY = int(os.environ.get('MESSAGE_RETRY_BASE_DELAY', '60'))   # seconds
MESSAGE_RETRY_MAX_DELAY = int(os.environ.get('MESSAGE_RETRY_MAX_DELAY', '3600'))   # seconds
MESSAGE_RETRY_JITTER = float(os.environ.get('MESSAGE_RETRY_JITTER', '0.25'))       # ±25%
MESSAGE_PROCESSING_TIMEOUT_MINUTES = int(os.environ.get('MESSAGE_PROCESSING_TIMEOUT_MINUTES', '10'))
MESSAGE_QUEUED_TIMEOUT_MINUTES = int(os.environ.get('MESSAGE_QUEUED_TIMEOUT_MINUTES', '5'))

CELERY_BEAT_SCHEDULE = {
    'dispatch-due-messages': {
        'task': 'app.celery.dispatch_due_messages',
        'schedule': 60.0,  # every 60 seconds
    },
    'cleanup-stale-media-blobs': {
        'task': 'app.celery.cleanup_stale_media_blobs',
        'schedule': 86400.0,  # every 24 hours
    },
    'generate-monthly-invoices': {
        'task': 'app.celery.generate_monthly_invoices',
        'schedule': crontab(day_of_month=1, hour=2, minute=0),  # 1st of month, 2:00 AM
    },
}
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Redis SSL — required for Azure Cache for Redis (rediss:// URLs)
def _ensure_redis_ssl(url):
    if url and url.startswith('rediss://') and 'ssl_cert_reqs' not in url:
        sep = '&' if '?' in url else '?'
        return url + sep + 'ssl_cert_reqs=CERT_NONE'
    return url

CELERY_BROKER_URL = _ensure_redis_ssl(CELERY_BROKER_URL)
CELERY_RESULT_BACKEND = _ensure_redis_ssl(CELERY_RESULT_BACKEND)

if CELERY_BROKER_URL and CELERY_BROKER_URL.startswith('rediss://'):
    CELERY_BROKER_USE_SSL = {'ssl_cert_reqs': _ssl.CERT_NONE}
    CELERY_REDIS_BACKEND_USE_SSL = {'ssl_cert_reqs': _ssl.CERT_NONE}


# SMS Provider
SMS_PROVIDER_CLASS = 'app.utils.welcorp.WelcorpSMSProvider'

# Welcorp SMS provider settings
WELCORP_BASE_URL = os.environ.get('WELCORP_BASE_URL', 'https://api.message-service.org/api/v1')
WELCORP_USERNAME = os.environ.get('WELCORP_USERNAME', '')
WELCORP_PASSWORD = os.environ.get('WELCORP_PASSWORD', '')
WELCORP_CALLBACK_SECRET = os.environ.get('WELCORP_CALLBACK_SECRET', '')



# Storage Provider Configuration
STORAGE_PROVIDER_CLASS = os.environ.get(
    'STORAGE_PROVIDER_CLASS',
    'app.utils.storage.MockStorageProvider'  # Default to mock for dev
)

STORAGE_PROVIDER_CONFIG = {
    # Azure Blob Storage settings (only used if AzureBlobStorageProvider selected)
    'account_name': os.environ.get('AZURE_STORAGE_ACCOUNT_NAME', ''),
    'account_key': os.environ.get('AZURE_STORAGE_ACCOUNT_KEY', ''),
    'container': os.environ.get('AZURE_CONTAINER', 'media'),
}

# Optional: Django media files (for LocalStorageProvider if implemented)
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# Sentry
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=False,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
    )


# Logging
class JSONFormatter(logging.Formatter):
    """Structured JSON log formatter for Azure App Service / Azure Monitor."""

    def format(self, record):
        log_entry = {
            'timestamp': self.formatTime(record),
            'level': record.levelname,
            'logger': record.name,
            'message': record.getMessage(),
        }
        # Include extra fields from RequestLoggingMiddleware
        for field in ('request_id', 'method', 'path', 'status', 'duration_ms',
                      'ip', 'user_agent', 'org_id', 'user_id'):
            value = getattr(record, field, None)
            if value is not None:
                log_entry[field] = value
        if record.exc_info and record.exc_info[0] is not None:
            log_entry['exception'] = self.formatException(record.exc_info)
        return json.dumps(log_entry)


LOG_FORMAT = os.environ.get('LOG_FORMAT', 'json' if not DEBUG else 'text')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'text': {
            'format': '%(asctime)s %(levelname)s [%(name)s] %(message)s',
        },
        'json': {
            '()': JSONFormatter,
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': LOG_FORMAT,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'app': {
            'handlers': ['console'],
            'level': os.environ.get('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
# test pipeline