/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppLayoutUsersRouteImport } from './routes/app/_layout.users'
import { Route as AppLayoutBillingRouteImport } from './routes/app/_layout.billing'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app/_layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutUsersRoute = AppLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutBillingRoute = AppLayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/app/billing': typeof AppLayoutBillingRoute
  '/app/users': typeof AppLayoutUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/app/billing': typeof AppLayoutBillingRoute
  '/app/users': typeof AppLayoutUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/app/_layout/billing': typeof AppLayoutBillingRoute
  '/app/_layout/users': typeof AppLayoutUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/app/billing'
    | '/app/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/terms' | '/app' | '/app/billing' | '/app/users'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/app/_layout'
    | '/app/_layout/billing'
    | '/app/_layout/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout/users': {
      id: '/app/_layout/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppLayoutUsersRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/billing': {
      id: '/app/_layout/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppLayoutBillingRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutBillingRoute: typeof AppLayoutBillingRoute
  AppLayoutUsersRoute: typeof AppLayoutUsersRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutBillingRoute: AppLayoutBillingRoute,
  AppLayoutUsersRoute: AppLayoutUsersRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
