# Generated by Django 6.0.2 on 2026-02-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisationmembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
