# Generated by Django 6.0.4 on 2026-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_billing_customer_id_and_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='unit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
