# Generated by Django 6.0.4 on 2026-05-12 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_trial_to_prepaid(apps, schema_editor):
    Organisation = apps.get_model('app', 'Organisation')
    Organisation.objects.filter(billing_mode='trial').update(billing_mode='prepaid')


def rename_prepaid_to_trial(apps, schema_editor):
    Organisation = apps.get_model('app', 'Organisation')
    Organisation.objects.filter(billing_mode='prepaid').update(billing_mode='trial')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_alphanumeric_sender_to_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='billing_mode',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('subscribed', 'Subscribed'), ('past_due', 'Past Due')], default='prepaid', max_length=20),
        ),
        migrations.RunPython(rename_trial_to_prepaid, rename_prepaid_to_trial),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_checkout_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('credit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_purchase', to='app.credittransaction')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_purchases',
                'indexes': [models.Index(fields=['organisation', '-created_at'], name='credit_purc_organis_a12ac4_idx')],
            },
        ),
    ]
